// 04-vue-exercise/Root.vue
<template>
  <div>
    <router-link to="vue-exercise/" style="padding: 16px; display: inline-block"
      >Vue Home</router-link
    >
    <router-link
      to="vue-exercise/subroute"
      style="padding: 16px; display: inline-block"
      >Vue Sub Route</router-link
    >
    <router-link to="/angular" style="padding: 16px; display: inline-block"
      >Angular</router-link
    >
    <div class="Texto">Vue exercise</div>
    <router-view></router-view>
  </div>
</template>
<style scope>
.Texto {
  color: green;
}
</style>

// 04-react-app/Root.jsx
import { BrowserRouter, Link, Route } from "react-router-dom";
import styles from "./ScopedStyle.module.css";

export default function Root(props) {
  const linkStyle = {
    padding: "16px",
    display: "inline-block",
  };
  return (
    <>
      <div className={styles["Texto"]}>React App</div>
      <BrowserRouter basename="/">
        <Link to="/react" style={linkStyle}>
          React home
        </Link>
        <Link to="/react/subroute" style={linkStyle}>
          React subroute
        </Link>
        <Link to="/vue" style={linkStyle}>
          Leave React
        </Link>
        <Route path="/react">
          <div>{props.name} is mounted</div>
        </Route>
        <Route path="/react" exact>
          <div>React Home</div>
        </Route>
        <Route path="/react/subroute">
          <div>Subroute</div>
        </Route>
      </BrowserRouter>
    </>
  );
}
